name: Deploy website
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
      Build_test:
          runs-on: ubuntu-latest
          steps:
             - name: Get the code
               uses: actions/checkout@v3
             - name: set the env
               uses: actions/setup-node@v3
               with:
                     node-version: 17
             - name: Intsall the dependencies
               run:  npm ci
             - name: Lint Testing
               run:  npm run lint
             - name: Testing
               run: npm run test
             - name: Building
               run: npm run build

  